#!/bin/sh

#if [ `ps -ef | grep -c mpvpaper` > 1 ]; then
    killall mpvpaper
#fi

#if [ `ps -ef | grep -c swaybg` > 1 ]; then
    killall swaybg
#fi

swaybg -o HDMI-A-1 -i `find ~/Pictures/Wallpapers -name "*.png" | shuf -n1`
