#!/usr/bin/env sh

volume=`pactl list sinks | grep '^[[:space:]]Volume:' | head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,'`
angle="$(( (($volume+2)/5) * 5 ))"
ico="$HOME/.config/dunst/icons/vol-${angle}.svg"
bar=$(seq -s "." $(($volume / 17)) | sed 's/[0-9]//g')
dunstify "t2" -a "$volume$bar" "$nsink" -i $ico -r 91190 -t 800
